version: "3.8"
services:
  ros2humble:
    container_name: ros2humble
    build:
      context: ./
    privileged: true
    shm_size: 1g
    environment:
      DISPLAY: $DISPLAY
      XDG_RUNTIME_DIR: /tmp
      QT_X11_NO_MITSHM: 1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    devices:
      - /dev/dri:/dev/dri
      - /dev/video0:/dev/video0
    network_mode: host
    tty: true
